// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: gritz/v1/gritz.proto

package gritzv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/icholy/gritz/internal/proto/gritz/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// GritzServiceName is the fully-qualified name of the GritzService service.
	GritzServiceName = "gritz.v1.GritzService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// GritzServicePingProcedure is the fully-qualified name of the GritzService's Ping RPC.
	GritzServicePingProcedure = "/gritz.v1.GritzService/Ping"
	// GritzServiceGetProfileProcedure is the fully-qualified name of the GritzService's GetProfile RPC.
	GritzServiceGetProfileProcedure = "/gritz.v1.GritzService/GetProfile"
	// GritzServiceListTasksProcedure is the fully-qualified name of the GritzService's ListTasks RPC.
	GritzServiceListTasksProcedure = "/gritz.v1.GritzService/ListTasks"
	// GritzServiceListRunnerTasksProcedure is the fully-qualified name of the GritzService's
	// ListRunnerTasks RPC.
	GritzServiceListRunnerTasksProcedure = "/gritz.v1.GritzService/ListRunnerTasks"
	// GritzServiceCreateTaskProcedure is the fully-qualified name of the GritzService's CreateTask RPC.
	GritzServiceCreateTaskProcedure = "/gritz.v1.GritzService/CreateTask"
	// GritzServiceGetTaskProcedure is the fully-qualified name of the GritzService's GetTask RPC.
	GritzServiceGetTaskProcedure = "/gritz.v1.GritzService/GetTask"
	// GritzServiceUpdateTaskProcedure is the fully-qualified name of the GritzService's UpdateTask RPC.
	GritzServiceUpdateTaskProcedure = "/gritz.v1.GritzService/UpdateTask"
	// GritzServiceArchiveTaskProcedure is the fully-qualified name of the GritzService's ArchiveTask
	// RPC.
	GritzServiceArchiveTaskProcedure = "/gritz.v1.GritzService/ArchiveTask"
	// GritzServiceUnarchiveTaskProcedure is the fully-qualified name of the GritzService's
	// UnarchiveTask RPC.
	GritzServiceUnarchiveTaskProcedure = "/gritz.v1.GritzService/UnarchiveTask"
	// GritzServiceCancelTaskProcedure is the fully-qualified name of the GritzService's CancelTask RPC.
	GritzServiceCancelTaskProcedure = "/gritz.v1.GritzService/CancelTask"
	// GritzServiceRestartTaskProcedure is the fully-qualified name of the GritzService's RestartTask
	// RPC.
	GritzServiceRestartTaskProcedure = "/gritz.v1.GritzService/RestartTask"
	// GritzServiceOpenShellProcedure is the fully-qualified name of the GritzService's OpenShell RPC.
	GritzServiceOpenShellProcedure = "/gritz.v1.GritzService/OpenShell"
	// GritzServiceUploadLogsProcedure is the fully-qualified name of the GritzService's UploadLogs RPC.
	GritzServiceUploadLogsProcedure = "/gritz.v1.GritzService/UploadLogs"
	// GritzServiceCreateLinkProcedure is the fully-qualified name of the GritzService's CreateLink RPC.
	GritzServiceCreateLinkProcedure = "/gritz.v1.GritzService/CreateLink"
	// GritzServiceListLinksProcedure is the fully-qualified name of the GritzService's ListLinks RPC.
	GritzServiceListLinksProcedure = "/gritz.v1.GritzService/ListLinks"
	// GritzServiceListExternalEventsProcedure is the fully-qualified name of the GritzService's
	// ListExternalEvents RPC.
	GritzServiceListExternalEventsProcedure = "/gritz.v1.GritzService/ListExternalEvents"
	// GritzServiceGetEventProcedure is the fully-qualified name of the GritzService's GetEvent RPC.
	GritzServiceGetEventProcedure = "/gritz.v1.GritzService/GetEvent"
	// GritzServiceDeleteEventProcedure is the fully-qualified name of the GritzService's DeleteEvent
	// RPC.
	GritzServiceDeleteEventProcedure = "/gritz.v1.GritzService/DeleteEvent"
	// GritzServiceListEventsByTaskProcedure is the fully-qualified name of the GritzService's
	// ListEventsByTask RPC.
	GritzServiceListEventsByTaskProcedure = "/gritz.v1.GritzService/ListEventsByTask"
	// GritzServiceSubmitRunnerEventsProcedure is the fully-qualified name of the GritzService's
	// SubmitRunnerEvents RPC.
	GritzServiceSubmitRunnerEventsProcedure = "/gritz.v1.GritzService/SubmitRunnerEvents"
	// GritzServiceCreateTaskTokenProcedure is the fully-qualified name of the GritzService's
	// CreateTaskToken RPC.
	GritzServiceCreateTaskTokenProcedure = "/gritz.v1.GritzService/CreateTaskToken"
	// GritzServiceRegisterWorkspacesProcedure is the fully-qualified name of the GritzService's
	// RegisterWorkspaces RPC.
	GritzServiceRegisterWorkspacesProcedure = "/gritz.v1.GritzService/RegisterWorkspaces"
	// GritzServiceListWorkspacesProcedure is the fully-qualified name of the GritzService's
	// ListWorkspaces RPC.
	GritzServiceListWorkspacesProcedure = "/gritz.v1.GritzService/ListWorkspaces"
	// GritzServiceClearWorkspacesProcedure is the fully-qualified name of the GritzService's
	// ClearWorkspaces RPC.
	GritzServiceClearWorkspacesProcedure = "/gritz.v1.GritzService/ClearWorkspaces"
	// GritzServiceCreateKeyProcedure is the fully-qualified name of the GritzService's CreateKey RPC.
	GritzServiceCreateKeyProcedure = "/gritz.v1.GritzService/CreateKey"
	// GritzServiceListKeysProcedure is the fully-qualified name of the GritzService's ListKeys RPC.
	GritzServiceListKeysProcedure = "/gritz.v1.GritzService/ListKeys"
	// GritzServiceDeleteKeyProcedure is the fully-qualified name of the GritzService's DeleteKey RPC.
	GritzServiceDeleteKeyProcedure = "/gritz.v1.GritzService/DeleteKey"
	// GritzServiceUnlinkGitHubAccountProcedure is the fully-qualified name of the GritzService's
	// UnlinkGitHubAccount RPC.
	GritzServiceUnlinkGitHubAccountProcedure = "/gritz.v1.GritzService/UnlinkGitHubAccount"
	// GritzServiceLinkGitHubInstallationProcedure is the fully-qualified name of the GritzService's
	// LinkGitHubInstallation RPC.
	GritzServiceLinkGitHubInstallationProcedure = "/gritz.v1.GritzService/LinkGitHubInstallation"
	// GritzServiceUnlinkAtlassianAccountProcedure is the fully-qualified name of the GritzService's
	// UnlinkAtlassianAccount RPC.
	GritzServiceUnlinkAtlassianAccountProcedure = "/gritz.v1.GritzService/UnlinkAtlassianAccount"
	// GritzServiceCreateOrgProcedure is the fully-qualified name of the GritzService's CreateOrg RPC.
	GritzServiceCreateOrgProcedure = "/gritz.v1.GritzService/CreateOrg"
	// GritzServiceListOrgsProcedure is the fully-qualified name of the GritzService's ListOrgs RPC.
	GritzServiceListOrgsProcedure = "/gritz.v1.GritzService/ListOrgs"
	// GritzServiceDeleteOrgProcedure is the fully-qualified name of the GritzService's DeleteOrg RPC.
	GritzServiceDeleteOrgProcedure = "/gritz.v1.GritzService/DeleteOrg"
	// GritzServiceAddOrgMemberProcedure is the fully-qualified name of the GritzService's AddOrgMember
	// RPC.
	GritzServiceAddOrgMemberProcedure = "/gritz.v1.GritzService/AddOrgMember"
	// GritzServiceRemoveOrgMemberProcedure is the fully-qualified name of the GritzService's
	// RemoveOrgMember RPC.
	GritzServiceRemoveOrgMemberProcedure = "/gritz.v1.GritzService/RemoveOrgMember"
	// GritzServiceListOrgMembersProcedure is the fully-qualified name of the GritzService's
	// ListOrgMembers RPC.
	GritzServiceListOrgMembersProcedure = "/gritz.v1.GritzService/ListOrgMembers"
	// GritzServiceGetOrgSettingsProcedure is the fully-qualified name of the GritzService's
	// GetOrgSettings RPC.
	GritzServiceGetOrgSettingsProcedure = "/gritz.v1.GritzService/GetOrgSettings"
	// GritzServiceGenerateAtlassianWebhookSecretProcedure is the fully-qualified name of the
	// GritzService's GenerateAtlassianWebhookSecret RPC.
	GritzServiceGenerateAtlassianWebhookSecretProcedure = "/gritz.v1.GritzService/GenerateAtlassianWebhookSecret"
	// GritzServiceGetRoutingRulesProcedure is the fully-qualified name of the GritzService's
	// GetRoutingRules RPC.
	GritzServiceGetRoutingRulesProcedure = "/gritz.v1.GritzService/GetRoutingRules"
	// GritzServiceSetRoutingRulesProcedure is the fully-qualified name of the GritzService's
	// SetRoutingRules RPC.
	GritzServiceSetRoutingRulesProcedure = "/gritz.v1.GritzService/SetRoutingRules"
	// GritzServiceGetEventTypesProcedure is the fully-qualified name of the GritzService's
	// GetEventTypes RPC.
	GritzServiceGetEventTypesProcedure = "/gritz.v1.GritzService/GetEventTypes"
	// GritzServiceTestEventProcedure is the fully-qualified name of the GritzService's TestEvent RPC.
	GritzServiceTestEventProcedure = "/gritz.v1.GritzService/TestEvent"
	// GritzServiceCreateGitHubTokenProcedure is the fully-qualified name of the GritzService's
	// CreateGitHubToken RPC.
	GritzServiceCreateGitHubTokenProcedure = "/gritz.v1.GritzService/CreateGitHubToken"
	// GritzServiceCreateScheduleProcedure is the fully-qualified name of the GritzService's
	// CreateSchedule RPC.
	GritzServiceCreateScheduleProcedure = "/gritz.v1.GritzService/CreateSchedule"
	// GritzServiceGetScheduleProcedure is the fully-qualified name of the GritzService's GetSchedule
	// RPC.
	GritzServiceGetScheduleProcedure = "/gritz.v1.GritzService/GetSchedule"
	// GritzServiceListSchedulesProcedure is the fully-qualified name of the GritzService's
	// ListSchedules RPC.
	GritzServiceListSchedulesProcedure = "/gritz.v1.GritzService/ListSchedules"
	// GritzServiceUpdateScheduleProcedure is the fully-qualified name of the GritzService's
	// UpdateSchedule RPC.
	GritzServiceUpdateScheduleProcedure = "/gritz.v1.GritzService/UpdateSchedule"
	// GritzServiceDeleteScheduleProcedure is the fully-qualified name of the GritzService's
	// DeleteSchedule RPC.
	GritzServiceDeleteScheduleProcedure = "/gritz.v1.GritzService/DeleteSchedule"
	// GritzServiceSetScheduleEnabledProcedure is the fully-qualified name of the GritzService's
	// SetScheduleEnabled RPC.
	GritzServiceSetScheduleEnabledProcedure = "/gritz.v1.GritzService/SetScheduleEnabled"
	// GritzServiceRunScheduleProcedure is the fully-qualified name of the GritzService's RunSchedule
	// RPC.
	GritzServiceRunScheduleProcedure = "/gritz.v1.GritzService/RunSchedule"
)

// GritzServiceClient is a client for the gritz.v1.GritzService service.
type GritzServiceClient interface {
	Ping(context.Context, *v1.PingRequest) (*v1.PingResponse, error)
	GetProfile(context.Context, *v1.GetProfileRequest) (*v1.GetProfileResponse, error)
	ListTasks(context.Context, *v1.ListTasksRequest) (*v1.ListTasksResponse, error)
	ListRunnerTasks(context.Context, *v1.ListRunnerTasksRequest) (*v1.ListRunnerTasksResponse, error)
	CreateTask(context.Context, *v1.CreateTaskRequest) (*v1.CreateTaskResponse, error)
	GetTask(context.Context, *v1.GetTaskRequest) (*v1.GetTaskResponse, error)
	UpdateTask(context.Context, *v1.UpdateTaskRequest) (*v1.UpdateTaskResponse, error)
	ArchiveTask(context.Context, *v1.ArchiveTaskRequest) (*v1.ArchiveTaskResponse, error)
	UnarchiveTask(context.Context, *v1.UnarchiveTaskRequest) (*v1.UnarchiveTaskResponse, error)
	CancelTask(context.Context, *v1.CancelTaskRequest) (*v1.CancelTaskResponse, error)
	RestartTask(context.Context, *v1.RestartTaskRequest) (*v1.RestartTaskResponse, error)
	OpenShell(context.Context, *v1.OpenShellRequest) (*v1.OpenShellResponse, error)
	UploadLogs(context.Context, *v1.UploadLogsRequest) (*v1.UploadLogsResponse, error)
	CreateLink(context.Context, *v1.CreateLinkRequest) (*v1.CreateLinkResponse, error)
	ListLinks(context.Context, *v1.ListLinksRequest) (*v1.ListLinksResponse, error)
	ListExternalEvents(context.Context, *v1.ListExternalEventsRequest) (*v1.ListExternalEventsResponse, error)
	GetEvent(context.Context, *v1.GetEventRequest) (*v1.GetEventResponse, error)
	DeleteEvent(context.Context, *v1.DeleteEventRequest) (*v1.DeleteEventResponse, error)
	ListEventsByTask(context.Context, *v1.ListEventsByTaskRequest) (*v1.ListEventsByTaskResponse, error)
	SubmitRunnerEvents(context.Context, *v1.SubmitRunnerEventsRequest) (*v1.SubmitRunnerEventsResponse, error)
	CreateTaskToken(context.Context, *v1.CreateTaskTokenRequest) (*v1.CreateTaskTokenResponse, error)
	RegisterWorkspaces(context.Context, *v1.RegisterWorkspacesRequest) (*v1.RegisterWorkspacesResponse, error)
	ListWorkspaces(context.Context, *v1.ListWorkspacesRequest) (*v1.ListWorkspacesResponse, error)
	ClearWorkspaces(context.Context, *v1.ClearWorkspacesRequest) (*v1.ClearWorkspacesResponse, error)
	CreateKey(context.Context, *v1.CreateKeyRequest) (*v1.CreateKeyResponse, error)
	ListKeys(context.Context, *v1.ListKeysRequest) (*v1.ListKeysResponse, error)
	DeleteKey(context.Context, *v1.DeleteKeyRequest) (*v1.DeleteKeyResponse, error)
	UnlinkGitHubAccount(context.Context, *v1.UnlinkGitHubAccountRequest) (*v1.UnlinkGitHubAccountResponse, error)
	LinkGitHubInstallation(context.Context, *v1.LinkGitHubInstallationRequest) (*v1.LinkGitHubInstallationResponse, error)
	UnlinkAtlassianAccount(context.Context, *v1.UnlinkAtlassianAccountRequest) (*v1.UnlinkAtlassianAccountResponse, error)
	CreateOrg(context.Context, *v1.CreateOrgRequest) (*v1.CreateOrgResponse, error)
	ListOrgs(context.Context, *v1.ListOrgsRequest) (*v1.ListOrgsResponse, error)
	DeleteOrg(context.Context, *v1.DeleteOrgRequest) (*v1.DeleteOrgResponse, error)
	AddOrgMember(context.Context, *v1.AddOrgMemberRequest) (*v1.AddOrgMemberResponse, error)
	RemoveOrgMember(context.Context, *v1.RemoveOrgMemberRequest) (*v1.RemoveOrgMemberResponse, error)
	ListOrgMembers(context.Context, *v1.ListOrgMembersRequest) (*v1.ListOrgMembersResponse, error)
	GetOrgSettings(context.Context, *v1.GetOrgSettingsRequest) (*v1.GetOrgSettingsResponse, error)
	GenerateAtlassianWebhookSecret(context.Context, *v1.GenerateAtlassianWebhookSecretRequest) (*v1.GenerateAtlassianWebhookSecretResponse, error)
	GetRoutingRules(context.Context, *v1.GetRoutingRulesRequest) (*v1.GetRoutingRulesResponse, error)
	SetRoutingRules(context.Context, *v1.SetRoutingRulesRequest) (*v1.SetRoutingRulesResponse, error)
	GetEventTypes(context.Context, *v1.GetEventTypesRequest) (*v1.GetEventTypesResponse, error)
	TestEvent(context.Context, *v1.TestEventRequest) (*v1.TestEventResponse, error)
	CreateGitHubToken(context.Context, *v1.CreateGitHubTokenRequest) (*v1.CreateGitHubTokenResponse, error)
	CreateSchedule(context.Context, *v1.CreateScheduleRequest) (*v1.CreateScheduleResponse, error)
	GetSchedule(context.Context, *v1.GetScheduleRequest) (*v1.GetScheduleResponse, error)
	ListSchedules(context.Context, *v1.ListSchedulesRequest) (*v1.ListSchedulesResponse, error)
	UpdateSchedule(context.Context, *v1.UpdateScheduleRequest) (*v1.UpdateScheduleResponse, error)
	DeleteSchedule(context.Context, *v1.DeleteScheduleRequest) (*v1.DeleteScheduleResponse, error)
	SetScheduleEnabled(context.Context, *v1.SetScheduleEnabledRequest) (*v1.SetScheduleEnabledResponse, error)
	RunSchedule(context.Context, *v1.RunScheduleRequest) (*v1.RunScheduleResponse, error)
}

// NewGritzServiceClient constructs a client for the gritz.v1.GritzService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewGritzServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) GritzServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	gritzServiceMethods := v1.File_gritz_v1_gritz_proto.Services().ByName("GritzService").Methods()
	return &gritzServiceClient{
		ping: connect.NewClient[v1.PingRequest, v1.PingResponse](
			httpClient,
			baseURL+GritzServicePingProcedure,
			connect.WithSchema(gritzServiceMethods.ByName("Ping")),
			connect.WithClientOptions(opts...),
		),
		getProfile: connect.NewClient[v1.GetProfileRequest, v1.GetProfileResponse](
			httpClient,
			baseURL+GritzServiceGetProfileProcedure,
			connect.WithSchema(gritzServiceMethods.ByName("GetProfile")),
			connect.WithClientOptions(opts...),
		),
		listTasks: connect.NewClient[v1.ListTasksRequest, v1.ListTasksResponse](
			httpClient,
			baseURL+GritzServiceListTasksProcedure,
			connect.WithSchema(gritzServiceMethods.ByName("ListTasks")),
			connect.WithClientOptions(opts...),
		),
		listRunnerTasks: connect.NewClient[v1.ListRunnerTasksRequest, v1.ListRunnerTasksResponse](
			httpClient,
			baseURL+GritzServiceListRunnerTasksProcedure,
			connect.WithSchema(gritzServiceMethods.ByName("ListRunnerTasks")),
			connect.WithClientOptions(opts...),
		),
		createTask: connect.NewClient[v1.CreateTaskRequest, v1.CreateTaskResponse](
			httpClient,
			baseURL+GritzServiceCreateTaskProcedure,
			connect.WithSchema(gritzServiceMethods.ByName("CreateTask")),
			connect.WithClientOptions(opts...),
		),
		getTask: connect.NewClient[v1.GetTaskRequest, v1.GetTaskResponse](
			httpClient,
			baseURL+GritzServiceGetTaskProcedure,
			connect.WithSchema(gritzServiceMethods.ByName("GetTask")),
			connect.WithClientOptions(opts...),
		),
		updateTask: connect.NewClient[v1.UpdateTaskRequest, v1.UpdateTaskResponse](
			httpClient,
			baseURL+GritzServiceUpdateTaskProcedure,
			connect.WithSchema(gritzServiceMethods.ByName("UpdateTask")),
			connect.WithClientOptions(opts...),
		),
		archiveTask: connect.NewClient[v1.ArchiveTaskRequest, v1.ArchiveTaskResponse](
			httpClient,
			baseURL+GritzServiceArchiveTaskProcedure,
			connect.WithSchema(gritzServiceMethods.ByName("ArchiveTask")),
			connect.WithClientOptions(opts...),
		),
		unarchiveTask: connect.NewClient[v1.UnarchiveTaskRequest, v1.UnarchiveTaskResponse](
			httpClient,
			baseURL+GritzServiceUnarchiveTaskProcedure,
			connect.WithSchema(gritzServiceMethods.ByName("UnarchiveTask")),
			connect.WithClientOptions(opts...),
		),
		cancelTask: connect.NewClient[v1.CancelTaskRequest, v1.CancelTaskResponse](
			httpClient,
			baseURL+GritzServiceCancelTaskProcedure,
			connect.WithSchema(gritzServiceMethods.ByName("CancelTask")),
			connect.WithClientOptions(opts...),
		),
		restartTask: connect.NewClient[v1.RestartTaskRequest, v1.RestartTaskResponse](
			httpClient,
			baseURL+GritzServiceRestartTaskProcedure,
			connect.WithSchema(gritzServiceMethods.ByName("RestartTask")),
			connect.WithClientOptions(opts...),
		),
		openShell: connect.NewClient[v1.OpenShellRequest, v1.OpenShellResponse](
			httpClient,
			baseURL+GritzServiceOpenShellProcedure,
			connect.WithSchema(gritzServiceMethods.ByName("OpenShell")),
			connect.WithClientOptions(opts...),
		),
		uploadLogs: connect.NewClient[v1.UploadLogsRequest, v1.UploadLogsResponse](
			httpClient,
			baseURL+GritzServiceUploadLogsProcedure,
			connect.WithSchema(gritzServiceMethods.ByName("UploadLogs")),
			connect.WithClientOptions(opts...),
		),
		createLink: connect.NewClient[v1.CreateLinkRequest, v1.CreateLinkResponse](
			httpClient,
			baseURL+GritzServiceCreateLinkProcedure,
			connect.WithSchema(gritzServiceMethods.ByName("CreateLink")),
			connect.WithClientOptions(opts...),
		),
		listLinks: connect.NewClient[v1.ListLinksRequest, v1.ListLinksResponse](
			httpClient,
			baseURL+GritzServiceListLinksProcedure,
			connect.WithSchema(gritzServiceMethods.ByName("ListLinks")),
			connect.WithClientOptions(opts...),
		),
		listExternalEvents: connect.NewClient[v1.ListExternalEventsRequest, v1.ListExternalEventsResponse](
			httpClient,
			baseURL+GritzServiceListExternalEventsProcedure,
			connect.WithSchema(gritzServiceMethods.ByName("ListExternalEvents")),
			connect.WithClientOptions(opts...),
		),
		getEvent: connect.NewClient[v1.GetEventRequest, v1.GetEventResponse](
			httpClient,
			baseURL+GritzServiceGetEventProcedure,
			connect.WithSchema(gritzServiceMethods.ByName("GetEvent")),
			connect.WithClientOptions(opts...),
		),
		deleteEvent: connect.NewClient[v1.DeleteEventRequest, v1.DeleteEventResponse](
			httpClient,
			baseURL+GritzServiceDeleteEventProcedure,
			connect.WithSchema(gritzServiceMethods.ByName("DeleteEvent")),
			connect.WithClientOptions(opts...),
		),
		listEventsByTask: connect.NewClient[v1.ListEventsByTaskRequest, v1.ListEventsByTaskResponse](
			httpClient,
			baseURL+GritzServiceListEventsByTaskProcedure,
			connect.WithSchema(gritzServiceMethods.ByName("ListEventsByTask")),
			connect.WithClientOptions(opts...),
		),
		submitRunnerEvents: connect.NewClient[v1.SubmitRunnerEventsRequest, v1.SubmitRunnerEventsResponse](
			httpClient,
			baseURL+GritzServiceSubmitRunnerEventsProcedure,
			connect.WithSchema(gritzServiceMethods.ByName("SubmitRunnerEvents")),
			connect.WithClientOptions(opts...),
		),
		createTaskToken: connect.NewClient[v1.CreateTaskTokenRequest, v1.CreateTaskTokenResponse](
			httpClient,
			baseURL+GritzServiceCreateTaskTokenProcedure,
			connect.WithSchema(gritzServiceMethods.ByName("CreateTaskToken")),
			connect.WithClientOptions(opts...),
		),
		registerWorkspaces: connect.NewClient[v1.RegisterWorkspacesRequest, v1.RegisterWorkspacesResponse](
			httpClient,
			baseURL+GritzServiceRegisterWorkspacesProcedure,
			connect.WithSchema(gritzServiceMethods.ByName("RegisterWorkspaces")),
			connect.WithClientOptions(opts...),
		),
		listWorkspaces: connect.NewClient[v1.ListWorkspacesRequest, v1.ListWorkspacesResponse](
			httpClient,
			baseURL+GritzServiceListWorkspacesProcedure,
			connect.WithSchema(gritzServiceMethods.ByName("ListWorkspaces")),
			connect.WithClientOptions(opts...),
		),
		clearWorkspaces: connect.NewClient[v1.ClearWorkspacesRequest, v1.ClearWorkspacesResponse](
			httpClient,
			baseURL+GritzServiceClearWorkspacesProcedure,
			connect.WithSchema(gritzServiceMethods.ByName("ClearWorkspaces")),
			connect.WithClientOptions(opts...),
		),
		createKey: connect.NewClient[v1.CreateKeyRequest, v1.CreateKeyResponse](
			httpClient,
			baseURL+GritzServiceCreateKeyProcedure,
			connect.WithSchema(gritzServiceMethods.ByName("CreateKey")),
			connect.WithClientOptions(opts...),
		),
		listKeys: connect.NewClient[v1.ListKeysRequest, v1.ListKeysResponse](
			httpClient,
			baseURL+GritzServiceListKeysProcedure,
			connect.WithSchema(gritzServiceMethods.ByName("ListKeys")),
			connect.WithClientOptions(opts...),
		),
		deleteKey: connect.NewClient[v1.DeleteKeyRequest, v1.DeleteKeyResponse](
			httpClient,
			baseURL+GritzServiceDeleteKeyProcedure,
			connect.WithSchema(gritzServiceMethods.ByName("DeleteKey")),
			connect.WithClientOptions(opts...),
		),
		unlinkGitHubAccount: connect.NewClient[v1.UnlinkGitHubAccountRequest, v1.UnlinkGitHubAccountResponse](
			httpClient,
			baseURL+GritzServiceUnlinkGitHubAccountProcedure,
			connect.WithSchema(gritzServiceMethods.ByName("UnlinkGitHubAccount")),
			connect.WithClientOptions(opts...),
		),
		linkGitHubInstallation: connect.NewClient[v1.LinkGitHubInstallationRequest, v1.LinkGitHubInstallationResponse](
			httpClient,
			baseURL+GritzServiceLinkGitHubInstallationProcedure,
			connect.WithSchema(gritzServiceMethods.ByName("LinkGitHubInstallation")),
			connect.WithClientOptions(opts...),
		),
		unlinkAtlassianAccount: connect.NewClient[v1.UnlinkAtlassianAccountRequest, v1.UnlinkAtlassianAccountResponse](
			httpClient,
			baseURL+GritzServiceUnlinkAtlassianAccountProcedure,
			connect.WithSchema(gritzServiceMethods.ByName("UnlinkAtlassianAccount")),
			connect.WithClientOptions(opts...),
		),
		createOrg: connect.NewClient[v1.CreateOrgRequest, v1.CreateOrgResponse](
			httpClient,
			baseURL+GritzServiceCreateOrgProcedure,
			connect.WithSchema(gritzServiceMethods.ByName("CreateOrg")),
			connect.WithClientOptions(opts...),
		),
		listOrgs: connect.NewClient[v1.ListOrgsRequest, v1.ListOrgsResponse](
			httpClient,
			baseURL+GritzServiceListOrgsProcedure,
			connect.WithSchema(gritzServiceMethods.ByName("ListOrgs")),
			connect.WithClientOptions(opts...),
		),
		deleteOrg: connect.NewClient[v1.DeleteOrgRequest, v1.DeleteOrgResponse](
			httpClient,
			baseURL+GritzServiceDeleteOrgProcedure,
			connect.WithSchema(gritzServiceMethods.ByName("DeleteOrg")),
			connect.WithClientOptions(opts...),
		),
		addOrgMember: connect.NewClient[v1.AddOrgMemberRequest, v1.AddOrgMemberResponse](
			httpClient,
			baseURL+GritzServiceAddOrgMemberProcedure,
			connect.WithSchema(gritzServiceMethods.ByName("AddOrgMember")),
			connect.WithClientOptions(opts...),
		),
		removeOrgMember: connect.NewClient[v1.RemoveOrgMemberRequest, v1.RemoveOrgMemberResponse](
			httpClient,
			baseURL+GritzServiceRemoveOrgMemberProcedure,
			connect.WithSchema(gritzServiceMethods.ByName("RemoveOrgMember")),
			connect.WithClientOptions(opts...),
		),
		listOrgMembers: connect.NewClient[v1.ListOrgMembersRequest, v1.ListOrgMembersResponse](
			httpClient,
			baseURL+GritzServiceListOrgMembersProcedure,
			connect.WithSchema(gritzServiceMethods.ByName("ListOrgMembers")),
			connect.WithClientOptions(opts...),
		),
		getOrgSettings: connect.NewClient[v1.GetOrgSettingsRequest, v1.GetOrgSettingsResponse](
			httpClient,
			baseURL+GritzServiceGetOrgSettingsProcedure,
			connect.WithSchema(gritzServiceMethods.ByName("GetOrgSettings")),
			connect.WithClientOptions(opts...),
		),
		generateAtlassianWebhookSecret: connect.NewClient[v1.GenerateAtlassianWebhookSecretRequest, v1.GenerateAtlassianWebhookSecretResponse](
			httpClient,
			baseURL+GritzServiceGenerateAtlassianWebhookSecretProcedure,
			connect.WithSchema(gritzServiceMethods.ByName("GenerateAtlassianWebhookSecret")),
			connect.WithClientOptions(opts...),
		),
		getRoutingRules: connect.NewClient[v1.GetRoutingRulesRequest, v1.GetRoutingRulesResponse](
			httpClient,
			baseURL+GritzServiceGetRoutingRulesProcedure,
			connect.WithSchema(gritzServiceMethods.ByName("GetRoutingRules")),
			connect.WithClientOptions(opts...),
		),
		setRoutingRules: connect.NewClient[v1.SetRoutingRulesRequest, v1.SetRoutingRulesResponse](
			httpClient,
			baseURL+GritzServiceSetRoutingRulesProcedure,
			connect.WithSchema(gritzServiceMethods.ByName("SetRoutingRules")),
			connect.WithClientOptions(opts...),
		),
		getEventTypes: connect.NewClient[v1.GetEventTypesRequest, v1.GetEventTypesResponse](
			httpClient,
			baseURL+GritzServiceGetEventTypesProcedure,
			connect.WithSchema(gritzServiceMethods.ByName("GetEventTypes")),
			connect.WithClientOptions(opts...),
		),
		testEvent: connect.NewClient[v1.TestEventRequest, v1.TestEventResponse](
			httpClient,
			baseURL+GritzServiceTestEventProcedure,
			connect.WithSchema(gritzServiceMethods.ByName("TestEvent")),
			connect.WithClientOptions(opts...),
		),
		createGitHubToken: connect.NewClient[v1.CreateGitHubTokenRequest, v1.CreateGitHubTokenResponse](
			httpClient,
			baseURL+GritzServiceCreateGitHubTokenProcedure,
			connect.WithSchema(gritzServiceMethods.ByName("CreateGitHubToken")),
			connect.WithClientOptions(opts...),
		),
		createSchedule: connect.NewClient[v1.CreateScheduleRequest, v1.CreateScheduleResponse](
			httpClient,
			baseURL+GritzServiceCreateScheduleProcedure,
			connect.WithSchema(gritzServiceMethods.ByName("CreateSchedule")),
			connect.WithClientOptions(opts...),
		),
		getSchedule: connect.NewClient[v1.GetScheduleRequest, v1.GetScheduleResponse](
			httpClient,
			baseURL+GritzServiceGetScheduleProcedure,
			connect.WithSchema(gritzServiceMethods.ByName("GetSchedule")),
			connect.WithClientOptions(opts...),
		),
		listSchedules: connect.NewClient[v1.ListSchedulesRequest, v1.ListSchedulesResponse](
			httpClient,
			baseURL+GritzServiceListSchedulesProcedure,
			connect.WithSchema(gritzServiceMethods.ByName("ListSchedules")),
			connect.WithClientOptions(opts...),
		),
		updateSchedule: connect.NewClient[v1.UpdateScheduleRequest, v1.UpdateScheduleResponse](
			httpClient,
			baseURL+GritzServiceUpdateScheduleProcedure,
			connect.WithSchema(gritzServiceMethods.ByName("UpdateSchedule")),
			connect.WithClientOptions(opts...),
		),
		deleteSchedule: connect.NewClient[v1.DeleteScheduleRequest, v1.DeleteScheduleResponse](
			httpClient,
			baseURL+GritzServiceDeleteScheduleProcedure,
			connect.WithSchema(gritzServiceMethods.ByName("DeleteSchedule")),
			connect.WithClientOptions(opts...),
		),
		setScheduleEnabled: connect.NewClient[v1.SetScheduleEnabledRequest, v1.SetScheduleEnabledResponse](
			httpClient,
			baseURL+GritzServiceSetScheduleEnabledProcedure,
			connect.WithSchema(gritzServiceMethods.ByName("SetScheduleEnabled")),
			connect.WithClientOptions(opts...),
		),
		runSchedule: connect.NewClient[v1.RunScheduleRequest, v1.RunScheduleResponse](
			httpClient,
			baseURL+GritzServiceRunScheduleProcedure,
			connect.WithSchema(gritzServiceMethods.ByName("RunSchedule")),
			connect.WithClientOptions(opts...),
		),
	}
}

// gritzServiceClient implements GritzServiceClient.
type gritzServiceClient struct {
	ping                           *connect.Client[v1.PingRequest, v1.PingResponse]
	getProfile                     *connect.Client[v1.GetProfileRequest, v1.GetProfileResponse]
	listTasks                      *connect.Client[v1.ListTasksRequest, v1.ListTasksResponse]
	listRunnerTasks                *connect.Client[v1.ListRunnerTasksRequest, v1.ListRunnerTasksResponse]
	createTask                     *connect.Client[v1.CreateTaskRequest, v1.CreateTaskResponse]
	getTask                        *connect.Client[v1.GetTaskRequest, v1.GetTaskResponse]
	updateTask                     *connect.Client[v1.UpdateTaskRequest, v1.UpdateTaskResponse]
	archiveTask                    *connect.Client[v1.ArchiveTaskRequest, v1.ArchiveTaskResponse]
	unarchiveTask                  *connect.Client[v1.UnarchiveTaskRequest, v1.UnarchiveTaskResponse]
	cancelTask                     *connect.Client[v1.CancelTaskRequest, v1.CancelTaskResponse]
	restartTask                    *connect.Client[v1.RestartTaskRequest, v1.RestartTaskResponse]
	openShell                      *connect.Client[v1.OpenShellRequest, v1.OpenShellResponse]
	uploadLogs                     *connect.Client[v1.UploadLogsRequest, v1.UploadLogsResponse]
	createLink                     *connect.Client[v1.CreateLinkRequest, v1.CreateLinkResponse]
	listLinks                      *connect.Client[v1.ListLinksRequest, v1.ListLinksResponse]
	listExternalEvents             *connect.Client[v1.ListExternalEventsRequest, v1.ListExternalEventsResponse]
	getEvent                       *connect.Client[v1.GetEventRequest, v1.GetEventResponse]
	deleteEvent                    *connect.Client[v1.DeleteEventRequest, v1.DeleteEventResponse]
	listEventsByTask               *connect.Client[v1.ListEventsByTaskRequest, v1.ListEventsByTaskResponse]
	submitRunnerEvents             *connect.Client[v1.SubmitRunnerEventsRequest, v1.SubmitRunnerEventsResponse]
	createTaskToken                *connect.Client[v1.CreateTaskTokenRequest, v1.CreateTaskTokenResponse]
	registerWorkspaces             *connect.Client[v1.RegisterWorkspacesRequest, v1.RegisterWorkspacesResponse]
	listWorkspaces                 *connect.Client[v1.ListWorkspacesRequest, v1.ListWorkspacesResponse]
	clearWorkspaces                *connect.Client[v1.ClearWorkspacesRequest, v1.ClearWorkspacesResponse]
	createKey                      *connect.Client[v1.CreateKeyRequest, v1.CreateKeyResponse]
	listKeys                       *connect.Client[v1.ListKeysRequest, v1.ListKeysResponse]
	deleteKey                      *connect.Client[v1.DeleteKeyRequest, v1.DeleteKeyResponse]
	unlinkGitHubAccount            *connect.Client[v1.UnlinkGitHubAccountRequest, v1.UnlinkGitHubAccountResponse]
	linkGitHubInstallation         *connect.Client[v1.LinkGitHubInstallationRequest, v1.LinkGitHubInstallationResponse]
	unlinkAtlassianAccount         *connect.Client[v1.UnlinkAtlassianAccountRequest, v1.UnlinkAtlassianAccountResponse]
	createOrg                      *connect.Client[v1.CreateOrgRequest, v1.CreateOrgResponse]
	listOrgs                       *connect.Client[v1.ListOrgsRequest, v1.ListOrgsResponse]
	deleteOrg                      *connect.Client[v1.DeleteOrgRequest, v1.DeleteOrgResponse]
	addOrgMember                   *connect.Client[v1.AddOrgMemberRequest, v1.AddOrgMemberResponse]
	removeOrgMember                *connect.Client[v1.RemoveOrgMemberRequest, v1.RemoveOrgMemberResponse]
	listOrgMembers                 *connect.Client[v1.ListOrgMembersRequest, v1.ListOrgMembersResponse]
	getOrgSettings                 *connect.Client[v1.GetOrgSettingsRequest, v1.GetOrgSettingsResponse]
	generateAtlassianWebhookSecret *connect.Client[v1.GenerateAtlassianWebhookSecretRequest, v1.GenerateAtlassianWebhookSecretResponse]
	getRoutingRules                *connect.Client[v1.GetRoutingRulesRequest, v1.GetRoutingRulesResponse]
	setRoutingRules                *connect.Client[v1.SetRoutingRulesRequest, v1.SetRoutingRulesResponse]
	getEventTypes                  *connect.Client[v1.GetEventTypesRequest, v1.GetEventTypesResponse]
	testEvent                      *connect.Client[v1.TestEventRequest, v1.TestEventResponse]
	createGitHubToken              *connect.Client[v1.CreateGitHubTokenRequest, v1.CreateGitHubTokenResponse]
	createSchedule                 *connect.Client[v1.CreateScheduleRequest, v1.CreateScheduleResponse]
	getSchedule                    *connect.Client[v1.GetScheduleRequest, v1.GetScheduleResponse]
	listSchedules                  *connect.Client[v1.ListSchedulesRequest, v1.ListSchedulesResponse]
	updateSchedule                 *connect.Client[v1.UpdateScheduleRequest, v1.UpdateScheduleResponse]
	deleteSchedule                 *connect.Client[v1.DeleteScheduleRequest, v1.DeleteScheduleResponse]
	setScheduleEnabled             *connect.Client[v1.SetScheduleEnabledRequest, v1.SetScheduleEnabledResponse]
	runSchedule                    *connect.Client[v1.RunScheduleRequest, v1.RunScheduleResponse]
}

// Ping calls gritz.v1.GritzService.Ping.
func (c *gritzServiceClient) Ping(ctx context.Context, req *v1.PingRequest) (*v1.PingResponse, error) {
	response, err := c.ping.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// GetProfile calls gritz.v1.GritzService.GetProfile.
func (c *gritzServiceClient) GetProfile(ctx context.Context, req *v1.GetProfileRequest) (*v1.GetProfileResponse, error) {
	response, err := c.getProfile.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ListTasks calls gritz.v1.GritzService.ListTasks.
func (c *gritzServiceClient) ListTasks(ctx context.Context, req *v1.ListTasksRequest) (*v1.ListTasksResponse, error) {
	response, err := c.listTasks.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ListRunnerTasks calls gritz.v1.GritzService.ListRunnerTasks.
func (c *gritzServiceClient) ListRunnerTasks(ctx context.Context, req *v1.ListRunnerTasksRequest) (*v1.ListRunnerTasksResponse, error) {
	response, err := c.listRunnerTasks.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// CreateTask calls gritz.v1.GritzService.CreateTask.
func (c *gritzServiceClient) CreateTask(ctx context.Context, req *v1.CreateTaskRequest) (*v1.CreateTaskResponse, error) {
	response, err := c.createTask.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// GetTask calls gritz.v1.GritzService.GetTask.
func (c *gritzServiceClient) GetTask(ctx context.Context, req *v1.GetTaskRequest) (*v1.GetTaskResponse, error) {
	response, err := c.getTask.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// UpdateTask calls gritz.v1.GritzService.UpdateTask.
func (c *gritzServiceClient) UpdateTask(ctx context.Context, req *v1.UpdateTaskRequest) (*v1.UpdateTaskResponse, error) {
	response, err := c.updateTask.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ArchiveTask calls gritz.v1.GritzService.ArchiveTask.
func (c *gritzServiceClient) ArchiveTask(ctx context.Context, req *v1.ArchiveTaskRequest) (*v1.ArchiveTaskResponse, error) {
	response, err := c.archiveTask.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// UnarchiveTask calls gritz.v1.GritzService.UnarchiveTask.
func (c *gritzServiceClient) UnarchiveTask(ctx context.Context, req *v1.UnarchiveTaskRequest) (*v1.UnarchiveTaskResponse, error) {
	response, err := c.unarchiveTask.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// CancelTask calls gritz.v1.GritzService.CancelTask.
func (c *gritzServiceClient) CancelTask(ctx context.Context, req *v1.CancelTaskRequest) (*v1.CancelTaskResponse, error) {
	response, err := c.cancelTask.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// RestartTask calls gritz.v1.GritzService.RestartTask.
func (c *gritzServiceClient) RestartTask(ctx context.Context, req *v1.RestartTaskRequest) (*v1.RestartTaskResponse, error) {
	response, err := c.restartTask.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// OpenShell calls gritz.v1.GritzService.OpenShell.
func (c *gritzServiceClient) OpenShell(ctx context.Context, req *v1.OpenShellRequest) (*v1.OpenShellResponse, error) {
	response, err := c.openShell.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// UploadLogs calls gritz.v1.GritzService.UploadLogs.
func (c *gritzServiceClient) UploadLogs(ctx context.Context, req *v1.UploadLogsRequest) (*v1.UploadLogsResponse, error) {
	response, err := c.uploadLogs.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// CreateLink calls gritz.v1.GritzService.CreateLink.
func (c *gritzServiceClient) CreateLink(ctx context.Context, req *v1.CreateLinkRequest) (*v1.CreateLinkResponse, error) {
	response, err := c.createLink.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ListLinks calls gritz.v1.GritzService.ListLinks.
func (c *gritzServiceClient) ListLinks(ctx context.Context, req *v1.ListLinksRequest) (*v1.ListLinksResponse, error) {
	response, err := c.listLinks.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ListExternalEvents calls gritz.v1.GritzService.ListExternalEvents.
func (c *gritzServiceClient) ListExternalEvents(ctx context.Context, req *v1.ListExternalEventsRequest) (*v1.ListExternalEventsResponse, error) {
	response, err := c.listExternalEvents.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// GetEvent calls gritz.v1.GritzService.GetEvent.
func (c *gritzServiceClient) GetEvent(ctx context.Context, req *v1.GetEventRequest) (*v1.GetEventResponse, error) {
	response, err := c.getEvent.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// DeleteEvent calls gritz.v1.GritzService.DeleteEvent.
func (c *gritzServiceClient) DeleteEvent(ctx context.Context, req *v1.DeleteEventRequest) (*v1.DeleteEventResponse, error) {
	response, err := c.deleteEvent.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ListEventsByTask calls gritz.v1.GritzService.ListEventsByTask.
func (c *gritzServiceClient) ListEventsByTask(ctx context.Context, req *v1.ListEventsByTaskRequest) (*v1.ListEventsByTaskResponse, error) {
	response, err := c.listEventsByTask.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// SubmitRunnerEvents calls gritz.v1.GritzService.SubmitRunnerEvents.
func (c *gritzServiceClient) SubmitRunnerEvents(ctx context.Context, req *v1.SubmitRunnerEventsRequest) (*v1.SubmitRunnerEventsResponse, error) {
	response, err := c.submitRunnerEvents.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// CreateTaskToken calls gritz.v1.GritzService.CreateTaskToken.
func (c *gritzServiceClient) CreateTaskToken(ctx context.Context, req *v1.CreateTaskTokenRequest) (*v1.CreateTaskTokenResponse, error) {
	response, err := c.createTaskToken.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// RegisterWorkspaces calls gritz.v1.GritzService.RegisterWorkspaces.
func (c *gritzServiceClient) RegisterWorkspaces(ctx context.Context, req *v1.RegisterWorkspacesRequest) (*v1.RegisterWorkspacesResponse, error) {
	response, err := c.registerWorkspaces.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ListWorkspaces calls gritz.v1.GritzService.ListWorkspaces.
func (c *gritzServiceClient) ListWorkspaces(ctx context.Context, req *v1.ListWorkspacesRequest) (*v1.ListWorkspacesResponse, error) {
	response, err := c.listWorkspaces.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ClearWorkspaces calls gritz.v1.GritzService.ClearWorkspaces.
func (c *gritzServiceClient) ClearWorkspaces(ctx context.Context, req *v1.ClearWorkspacesRequest) (*v1.ClearWorkspacesResponse, error) {
	response, err := c.clearWorkspaces.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// CreateKey calls gritz.v1.GritzService.CreateKey.
func (c *gritzServiceClient) CreateKey(ctx context.Context, req *v1.CreateKeyRequest) (*v1.CreateKeyResponse, error) {
	response, err := c.createKey.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ListKeys calls gritz.v1.GritzService.ListKeys.
func (c *gritzServiceClient) ListKeys(ctx context.Context, req *v1.ListKeysRequest) (*v1.ListKeysResponse, error) {
	response, err := c.listKeys.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// DeleteKey calls gritz.v1.GritzService.DeleteKey.
func (c *gritzServiceClient) DeleteKey(ctx context.Context, req *v1.DeleteKeyRequest) (*v1.DeleteKeyResponse, error) {
	response, err := c.deleteKey.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// UnlinkGitHubAccount calls gritz.v1.GritzService.UnlinkGitHubAccount.
func (c *gritzServiceClient) UnlinkGitHubAccount(ctx context.Context, req *v1.UnlinkGitHubAccountRequest) (*v1.UnlinkGitHubAccountResponse, error) {
	response, err := c.unlinkGitHubAccount.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// LinkGitHubInstallation calls gritz.v1.GritzService.LinkGitHubInstallation.
func (c *gritzServiceClient) LinkGitHubInstallation(ctx context.Context, req *v1.LinkGitHubInstallationRequest) (*v1.LinkGitHubInstallationResponse, error) {
	response, err := c.linkGitHubInstallation.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// UnlinkAtlassianAccount calls gritz.v1.GritzService.UnlinkAtlassianAccount.
func (c *gritzServiceClient) UnlinkAtlassianAccount(ctx context.Context, req *v1.UnlinkAtlassianAccountRequest) (*v1.UnlinkAtlassianAccountResponse, error) {
	response, err := c.unlinkAtlassianAccount.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// CreateOrg calls gritz.v1.GritzService.CreateOrg.
func (c *gritzServiceClient) CreateOrg(ctx context.Context, req *v1.CreateOrgRequest) (*v1.CreateOrgResponse, error) {
	response, err := c.createOrg.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ListOrgs calls gritz.v1.GritzService.ListOrgs.
func (c *gritzServiceClient) ListOrgs(ctx context.Context, req *v1.ListOrgsRequest) (*v1.ListOrgsResponse, error) {
	response, err := c.listOrgs.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// DeleteOrg calls gritz.v1.GritzService.DeleteOrg.
func (c *gritzServiceClient) DeleteOrg(ctx context.Context, req *v1.DeleteOrgRequest) (*v1.DeleteOrgResponse, error) {
	response, err := c.deleteOrg.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// AddOrgMember calls gritz.v1.GritzService.AddOrgMember.
func (c *gritzServiceClient) AddOrgMember(ctx context.Context, req *v1.AddOrgMemberRequest) (*v1.AddOrgMemberResponse, error) {
	response, err := c.addOrgMember.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// RemoveOrgMember calls gritz.v1.GritzService.RemoveOrgMember.
func (c *gritzServiceClient) RemoveOrgMember(ctx context.Context, req *v1.RemoveOrgMemberRequest) (*v1.RemoveOrgMemberResponse, error) {
	response, err := c.removeOrgMember.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ListOrgMembers calls gritz.v1.GritzService.ListOrgMembers.
func (c *gritzServiceClient) ListOrgMembers(ctx context.Context, req *v1.ListOrgMembersRequest) (*v1.ListOrgMembersResponse, error) {
	response, err := c.listOrgMembers.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// GetOrgSettings calls gritz.v1.GritzService.GetOrgSettings.
func (c *gritzServiceClient) GetOrgSettings(ctx context.Context, req *v1.GetOrgSettingsRequest) (*v1.GetOrgSettingsResponse, error) {
	response, err := c.getOrgSettings.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// GenerateAtlassianWebhookSecret calls gritz.v1.GritzService.GenerateAtlassianWebhookSecret.
func (c *gritzServiceClient) GenerateAtlassianWebhookSecret(ctx context.Context, req *v1.GenerateAtlassianWebhookSecretRequest) (*v1.GenerateAtlassianWebhookSecretResponse, error) {
	response, err := c.generateAtlassianWebhookSecret.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// GetRoutingRules calls gritz.v1.GritzService.GetRoutingRules.
func (c *gritzServiceClient) GetRoutingRules(ctx context.Context, req *v1.GetRoutingRulesRequest) (*v1.GetRoutingRulesResponse, error) {
	response, err := c.getRoutingRules.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// SetRoutingRules calls gritz.v1.GritzService.SetRoutingRules.
func (c *gritzServiceClient) SetRoutingRules(ctx context.Context, req *v1.SetRoutingRulesRequest) (*v1.SetRoutingRulesResponse, error) {
	response, err := c.setRoutingRules.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// GetEventTypes calls gritz.v1.GritzService.GetEventTypes.
func (c *gritzServiceClient) GetEventTypes(ctx context.Context, req *v1.GetEventTypesRequest) (*v1.GetEventTypesResponse, error) {
	response, err := c.getEventTypes.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// TestEvent calls gritz.v1.GritzService.TestEvent.
func (c *gritzServiceClient) TestEvent(ctx context.Context, req *v1.TestEventRequest) (*v1.TestEventResponse, error) {
	response, err := c.testEvent.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// CreateGitHubToken calls gritz.v1.GritzService.CreateGitHubToken.
func (c *gritzServiceClient) CreateGitHubToken(ctx context.Context, req *v1.CreateGitHubTokenRequest) (*v1.CreateGitHubTokenResponse, error) {
	response, err := c.createGitHubToken.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// CreateSchedule calls gritz.v1.GritzService.CreateSchedule.
func (c *gritzServiceClient) CreateSchedule(ctx context.Context, req *v1.CreateScheduleRequest) (*v1.CreateScheduleResponse, error) {
	response, err := c.createSchedule.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// GetSchedule calls gritz.v1.GritzService.GetSchedule.
func (c *gritzServiceClient) GetSchedule(ctx context.Context, req *v1.GetScheduleRequest) (*v1.GetScheduleResponse, error) {
	response, err := c.getSchedule.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ListSchedules calls gritz.v1.GritzService.ListSchedules.
func (c *gritzServiceClient) ListSchedules(ctx context.Context, req *v1.ListSchedulesRequest) (*v1.ListSchedulesResponse, error) {
	response, err := c.listSchedules.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// UpdateSchedule calls gritz.v1.GritzService.UpdateSchedule.
func (c *gritzServiceClient) UpdateSchedule(ctx context.Context, req *v1.UpdateScheduleRequest) (*v1.UpdateScheduleResponse, error) {
	response, err := c.updateSchedule.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// DeleteSchedule calls gritz.v1.GritzService.DeleteSchedule.
func (c *gritzServiceClient) DeleteSchedule(ctx context.Context, req *v1.DeleteScheduleRequest) (*v1.DeleteScheduleResponse, error) {
	response, err := c.deleteSchedule.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// SetScheduleEnabled calls gritz.v1.GritzService.SetScheduleEnabled.
func (c *gritzServiceClient) SetScheduleEnabled(ctx context.Context, req *v1.SetScheduleEnabledRequest) (*v1.SetScheduleEnabledResponse, error) {
	response, err := c.setScheduleEnabled.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// RunSchedule calls gritz.v1.GritzService.RunSchedule.
func (c *gritzServiceClient) RunSchedule(ctx context.Context, req *v1.RunScheduleRequest) (*v1.RunScheduleResponse, error) {
	response, err := c.runSchedule.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// GritzServiceHandler is an implementation of the gritz.v1.GritzService service.
type GritzServiceHandler interface {
	Ping(context.Context, *v1.PingRequest) (*v1.PingResponse, error)
	GetProfile(context.Context, *v1.GetProfileRequest) (*v1.GetProfileResponse, error)
	ListTasks(context.Context, *v1.ListTasksRequest) (*v1.ListTasksResponse, error)
	ListRunnerTasks(context.Context, *v1.ListRunnerTasksRequest) (*v1.ListRunnerTasksResponse, error)
	CreateTask(context.Context, *v1.CreateTaskRequest) (*v1.CreateTaskResponse, error)
	GetTask(context.Context, *v1.GetTaskRequest) (*v1.GetTaskResponse, error)
	UpdateTask(context.Context, *v1.UpdateTaskRequest) (*v1.UpdateTaskResponse, error)
	ArchiveTask(context.Context, *v1.ArchiveTaskRequest) (*v1.ArchiveTaskResponse, error)
	UnarchiveTask(context.Context, *v1.UnarchiveTaskRequest) (*v1.UnarchiveTaskResponse, error)
	CancelTask(context.Context, *v1.CancelTaskRequest) (*v1.CancelTaskResponse, error)
	RestartTask(context.Context, *v1.RestartTaskRequest) (*v1.RestartTaskResponse, error)
	OpenShell(context.Context, *v1.OpenShellRequest) (*v1.OpenShellResponse, error)
	UploadLogs(context.Context, *v1.UploadLogsRequest) (*v1.UploadLogsResponse, error)
	CreateLink(context.Context, *v1.CreateLinkRequest) (*v1.CreateLinkResponse, error)
	ListLinks(context.Context, *v1.ListLinksRequest) (*v1.ListLinksResponse, error)
	ListExternalEvents(context.Context, *v1.ListExternalEventsRequest) (*v1.ListExternalEventsResponse, error)
	GetEvent(context.Context, *v1.GetEventRequest) (*v1.GetEventResponse, error)
	DeleteEvent(context.Context, *v1.DeleteEventRequest) (*v1.DeleteEventResponse, error)
	ListEventsByTask(context.Context, *v1.ListEventsByTaskRequest) (*v1.ListEventsByTaskResponse, error)
	SubmitRunnerEvents(context.Context, *v1.SubmitRunnerEventsRequest) (*v1.SubmitRunnerEventsResponse, error)
	CreateTaskToken(context.Context, *v1.CreateTaskTokenRequest) (*v1.CreateTaskTokenResponse, error)
	RegisterWorkspaces(context.Context, *v1.RegisterWorkspacesRequest) (*v1.RegisterWorkspacesResponse, error)
	ListWorkspaces(context.Context, *v1.ListWorkspacesRequest) (*v1.ListWorkspacesResponse, error)
	ClearWorkspaces(context.Context, *v1.ClearWorkspacesRequest) (*v1.ClearWorkspacesResponse, error)
	CreateKey(context.Context, *v1.CreateKeyRequest) (*v1.CreateKeyResponse, error)
	ListKeys(context.Context, *v1.ListKeysRequest) (*v1.ListKeysResponse, error)
	DeleteKey(context.Context, *v1.DeleteKeyRequest) (*v1.DeleteKeyResponse, error)
	UnlinkGitHubAccount(context.Context, *v1.UnlinkGitHubAccountRequest) (*v1.UnlinkGitHubAccountResponse, error)
	LinkGitHubInstallation(context.Context, *v1.LinkGitHubInstallationRequest) (*v1.LinkGitHubInstallationResponse, error)
	UnlinkAtlassianAccount(context.Context, *v1.UnlinkAtlassianAccountRequest) (*v1.UnlinkAtlassianAccountResponse, error)
	CreateOrg(context.Context, *v1.CreateOrgRequest) (*v1.CreateOrgResponse, error)
	ListOrgs(context.Context, *v1.ListOrgsRequest) (*v1.ListOrgsResponse, error)
	DeleteOrg(context.Context, *v1.DeleteOrgRequest) (*v1.DeleteOrgResponse, error)
	AddOrgMember(context.Context, *v1.AddOrgMemberRequest) (*v1.AddOrgMemberResponse, error)
	RemoveOrgMember(context.Context, *v1.RemoveOrgMemberRequest) (*v1.RemoveOrgMemberResponse, error)
	ListOrgMembers(context.Context, *v1.ListOrgMembersRequest) (*v1.ListOrgMembersResponse, error)
	GetOrgSettings(context.Context, *v1.GetOrgSettingsRequest) (*v1.GetOrgSettingsResponse, error)
	GenerateAtlassianWebhookSecret(context.Context, *v1.GenerateAtlassianWebhookSecretRequest) (*v1.GenerateAtlassianWebhookSecretResponse, error)
	GetRoutingRules(context.Context, *v1.GetRoutingRulesRequest) (*v1.GetRoutingRulesResponse, error)
	SetRoutingRules(context.Context, *v1.SetRoutingRulesRequest) (*v1.SetRoutingRulesResponse, error)
	GetEventTypes(context.Context, *v1.GetEventTypesRequest) (*v1.GetEventTypesResponse, error)
	TestEvent(context.Context, *v1.TestEventRequest) (*v1.TestEventResponse, error)
	CreateGitHubToken(context.Context, *v1.CreateGitHubTokenRequest) (*v1.CreateGitHubTokenResponse, error)
	CreateSchedule(context.Context, *v1.CreateScheduleRequest) (*v1.CreateScheduleResponse, error)
	GetSchedule(context.Context, *v1.GetScheduleRequest) (*v1.GetScheduleResponse, error)
	ListSchedules(context.Context, *v1.ListSchedulesRequest) (*v1.ListSchedulesResponse, error)
	UpdateSchedule(context.Context, *v1.UpdateScheduleRequest) (*v1.UpdateScheduleResponse, error)
	DeleteSchedule(context.Context, *v1.DeleteScheduleRequest) (*v1.DeleteScheduleResponse, error)
	SetScheduleEnabled(context.Context, *v1.SetScheduleEnabledRequest) (*v1.SetScheduleEnabledResponse, error)
	RunSchedule(context.Context, *v1.RunScheduleRequest) (*v1.RunScheduleResponse, error)
}

// NewGritzServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewGritzServiceHandler(svc GritzServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	gritzServiceMethods := v1.File_gritz_v1_gritz_proto.Services().ByName("GritzService").Methods()
	gritzServicePingHandler := connect.NewUnaryHandlerSimple(
		GritzServicePingProcedure,
		svc.Ping,
		connect.WithSchema(gritzServiceMethods.ByName("Ping")),
		connect.WithHandlerOptions(opts...),
	)
	gritzServiceGetProfileHandler := connect.NewUnaryHandlerSimple(
		GritzServiceGetProfileProcedure,
		svc.GetProfile,
		connect.WithSchema(gritzServiceMethods.ByName("GetProfile")),
		connect.WithHandlerOptions(opts...),
	)
	gritzServiceListTasksHandler := connect.NewUnaryHandlerSimple(
		GritzServiceListTasksProcedure,
		svc.ListTasks,
		connect.WithSchema(gritzServiceMethods.ByName("ListTasks")),
		connect.WithHandlerOptions(opts...),
	)
	gritzServiceListRunnerTasksHandler := connect.NewUnaryHandlerSimple(
		GritzServiceListRunnerTasksProcedure,
		svc.ListRunnerTasks,
		connect.WithSchema(gritzServiceMethods.ByName("ListRunnerTasks")),
		connect.WithHandlerOptions(opts...),
	)
	gritzServiceCreateTaskHandler := connect.NewUnaryHandlerSimple(
		GritzServiceCreateTaskProcedure,
		svc.CreateTask,
		connect.WithSchema(gritzServiceMethods.ByName("CreateTask")),
		connect.WithHandlerOptions(opts...),
	)
	gritzServiceGetTaskHandler := connect.NewUnaryHandlerSimple(
		GritzServiceGetTaskProcedure,
		svc.GetTask,
		connect.WithSchema(gritzServiceMethods.ByName("GetTask")),
		connect.WithHandlerOptions(opts...),
	)
	gritzServiceUpdateTaskHandler := connect.NewUnaryHandlerSimple(
		GritzServiceUpdateTaskProcedure,
		svc.UpdateTask,
		connect.WithSchema(gritzServiceMethods.ByName("UpdateTask")),
		connect.WithHandlerOptions(opts...),
	)
	gritzServiceArchiveTaskHandler := connect.NewUnaryHandlerSimple(
		GritzServiceArchiveTaskProcedure,
		svc.ArchiveTask,
		connect.WithSchema(gritzServiceMethods.ByName("ArchiveTask")),
		connect.WithHandlerOptions(opts...),
	)
	gritzServiceUnarchiveTaskHandler := connect.NewUnaryHandlerSimple(
		GritzServiceUnarchiveTaskProcedure,
		svc.UnarchiveTask,
		connect.WithSchema(gritzServiceMethods.ByName("UnarchiveTask")),
		connect.WithHandlerOptions(opts...),
	)
	gritzServiceCancelTaskHandler := connect.NewUnaryHandlerSimple(
		GritzServiceCancelTaskProcedure,
		svc.CancelTask,
		connect.WithSchema(gritzServiceMethods.ByName("CancelTask")),
		connect.WithHandlerOptions(opts...),
	)
	gritzServiceRestartTaskHandler := connect.NewUnaryHandlerSimple(
		GritzServiceRestartTaskProcedure,
		svc.RestartTask,
		connect.WithSchema(gritzServiceMethods.ByName("RestartTask")),
		connect.WithHandlerOptions(opts...),
	)
	gritzServiceOpenShellHandler := connect.NewUnaryHandlerSimple(
		GritzServiceOpenShellProcedure,
		svc.OpenShell,
		connect.WithSchema(gritzServiceMethods.ByName("OpenShell")),
		connect.WithHandlerOptions(opts...),
	)
	gritzServiceUploadLogsHandler := connect.NewUnaryHandlerSimple(
		GritzServiceUploadLogsProcedure,
		svc.UploadLogs,
		connect.WithSchema(gritzServiceMethods.ByName("UploadLogs")),
		connect.WithHandlerOptions(opts...),
	)
	gritzServiceCreateLinkHandler := connect.NewUnaryHandlerSimple(
		GritzServiceCreateLinkProcedure,
		svc.CreateLink,
		connect.WithSchema(gritzServiceMethods.ByName("CreateLink")),
		connect.WithHandlerOptions(opts...),
	)
	gritzServiceListLinksHandler := connect.NewUnaryHandlerSimple(
		GritzServiceListLinksProcedure,
		svc.ListLinks,
		connect.WithSchema(gritzServiceMethods.ByName("ListLinks")),
		connect.WithHandlerOptions(opts...),
	)
	gritzServiceListExternalEventsHandler := connect.NewUnaryHandlerSimple(
		GritzServiceListExternalEventsProcedure,
		svc.ListExternalEvents,
		connect.WithSchema(gritzServiceMethods.ByName("ListExternalEvents")),
		connect.WithHandlerOptions(opts...),
	)
	gritzServiceGetEventHandler := connect.NewUnaryHandlerSimple(
		GritzServiceGetEventProcedure,
		svc.GetEvent,
		connect.WithSchema(gritzServiceMethods.ByName("GetEvent")),
		connect.WithHandlerOptions(opts...),
	)
	gritzServiceDeleteEventHandler := connect.NewUnaryHandlerSimple(
		GritzServiceDeleteEventProcedure,
		svc.DeleteEvent,
		connect.WithSchema(gritzServiceMethods.ByName("DeleteEvent")),
		connect.WithHandlerOptions(opts...),
	)
	gritzServiceListEventsByTaskHandler := connect.NewUnaryHandlerSimple(
		GritzServiceListEventsByTaskProcedure,
		svc.ListEventsByTask,
		connect.WithSchema(gritzServiceMethods.ByName("ListEventsByTask")),
		connect.WithHandlerOptions(opts...),
	)
	gritzServiceSubmitRunnerEventsHandler := connect.NewUnaryHandlerSimple(
		GritzServiceSubmitRunnerEventsProcedure,
		svc.SubmitRunnerEvents,
		connect.WithSchema(gritzServiceMethods.ByName("SubmitRunnerEvents")),
		connect.WithHandlerOptions(opts...),
	)
	gritzServiceCreateTaskTokenHandler := connect.NewUnaryHandlerSimple(
		GritzServiceCreateTaskTokenProcedure,
		svc.CreateTaskToken,
		connect.WithSchema(gritzServiceMethods.ByName("CreateTaskToken")),
		connect.WithHandlerOptions(opts...),
	)
	gritzServiceRegisterWorkspacesHandler := connect.NewUnaryHandlerSimple(
		GritzServiceRegisterWorkspacesProcedure,
		svc.RegisterWorkspaces,
		connect.WithSchema(gritzServiceMethods.ByName("RegisterWorkspaces")),
		connect.WithHandlerOptions(opts...),
	)
	gritzServiceListWorkspacesHandler := connect.NewUnaryHandlerSimple(
		GritzServiceListWorkspacesProcedure,
		svc.ListWorkspaces,
		connect.WithSchema(gritzServiceMethods.ByName("ListWorkspaces")),
		connect.WithHandlerOptions(opts...),
	)
	gritzServiceClearWorkspacesHandler := connect.NewUnaryHandlerSimple(
		GritzServiceClearWorkspacesProcedure,
		svc.ClearWorkspaces,
		connect.WithSchema(gritzServiceMethods.ByName("ClearWorkspaces")),
		connect.WithHandlerOptions(opts...),
	)
	gritzServiceCreateKeyHandler := connect.NewUnaryHandlerSimple(
		GritzServiceCreateKeyProcedure,
		svc.CreateKey,
		connect.WithSchema(gritzServiceMethods.ByName("CreateKey")),
		connect.WithHandlerOptions(opts...),
	)
	gritzServiceListKeysHandler := connect.NewUnaryHandlerSimple(
		GritzServiceListKeysProcedure,
		svc.ListKeys,
		connect.WithSchema(gritzServiceMethods.ByName("ListKeys")),
		connect.WithHandlerOptions(opts...),
	)
	gritzServiceDeleteKeyHandler := connect.NewUnaryHandlerSimple(
		GritzServiceDeleteKeyProcedure,
		svc.DeleteKey,
		connect.WithSchema(gritzServiceMethods.ByName("DeleteKey")),
		connect.WithHandlerOptions(opts...),
	)
	gritzServiceUnlinkGitHubAccountHandler := connect.NewUnaryHandlerSimple(
		GritzServiceUnlinkGitHubAccountProcedure,
		svc.UnlinkGitHubAccount,
		connect.WithSchema(gritzServiceMethods.ByName("UnlinkGitHubAccount")),
		connect.WithHandlerOptions(opts...),
	)
	gritzServiceLinkGitHubInstallationHandler := connect.NewUnaryHandlerSimple(
		GritzServiceLinkGitHubInstallationProcedure,
		svc.LinkGitHubInstallation,
		connect.WithSchema(gritzServiceMethods.ByName("LinkGitHubInstallation")),
		connect.WithHandlerOptions(opts...),
	)
	gritzServiceUnlinkAtlassianAccountHandler := connect.NewUnaryHandlerSimple(
		GritzServiceUnlinkAtlassianAccountProcedure,
		svc.UnlinkAtlassianAccount,
		connect.WithSchema(gritzServiceMethods.ByName("UnlinkAtlassianAccount")),
		connect.WithHandlerOptions(opts...),
	)
	gritzServiceCreateOrgHandler := connect.NewUnaryHandlerSimple(
		GritzServiceCreateOrgProcedure,
		svc.CreateOrg,
		connect.WithSchema(gritzServiceMethods.ByName("CreateOrg")),
		connect.WithHandlerOptions(opts...),
	)
	gritzServiceListOrgsHandler := connect.NewUnaryHandlerSimple(
		GritzServiceListOrgsProcedure,
		svc.ListOrgs,
		connect.WithSchema(gritzServiceMethods.ByName("ListOrgs")),
		connect.WithHandlerOptions(opts...),
	)
	gritzServiceDeleteOrgHandler := connect.NewUnaryHandlerSimple(
		GritzServiceDeleteOrgProcedure,
		svc.DeleteOrg,
		connect.WithSchema(gritzServiceMethods.ByName("DeleteOrg")),
		connect.WithHandlerOptions(opts...),
	)
	gritzServiceAddOrgMemberHandler := connect.NewUnaryHandlerSimple(
		GritzServiceAddOrgMemberProcedure,
		svc.AddOrgMember,
		connect.WithSchema(gritzServiceMethods.ByName("AddOrgMember")),
		connect.WithHandlerOptions(opts...),
	)
	gritzServiceRemoveOrgMemberHandler := connect.NewUnaryHandlerSimple(
		GritzServiceRemoveOrgMemberProcedure,
		svc.RemoveOrgMember,
		connect.WithSchema(gritzServiceMethods.ByName("RemoveOrgMember")),
		connect.WithHandlerOptions(opts...),
	)
	gritzServiceListOrgMembersHandler := connect.NewUnaryHandlerSimple(
		GritzServiceListOrgMembersProcedure,
		svc.ListOrgMembers,
		connect.WithSchema(gritzServiceMethods.ByName("ListOrgMembers")),
		connect.WithHandlerOptions(opts...),
	)
	gritzServiceGetOrgSettingsHandler := connect.NewUnaryHandlerSimple(
		GritzServiceGetOrgSettingsProcedure,
		svc.GetOrgSettings,
		connect.WithSchema(gritzServiceMethods.ByName("GetOrgSettings")),
		connect.WithHandlerOptions(opts...),
	)
	gritzServiceGenerateAtlassianWebhookSecretHandler := connect.NewUnaryHandlerSimple(
		GritzServiceGenerateAtlassianWebhookSecretProcedure,
		svc.GenerateAtlassianWebhookSecret,
		connect.WithSchema(gritzServiceMethods.ByName("GenerateAtlassianWebhookSecret")),
		connect.WithHandlerOptions(opts...),
	)
	gritzServiceGetRoutingRulesHandler := connect.NewUnaryHandlerSimple(
		GritzServiceGetRoutingRulesProcedure,
		svc.GetRoutingRules,
		connect.WithSchema(gritzServiceMethods.ByName("GetRoutingRules")),
		connect.WithHandlerOptions(opts...),
	)
	gritzServiceSetRoutingRulesHandler := connect.NewUnaryHandlerSimple(
		GritzServiceSetRoutingRulesProcedure,
		svc.SetRoutingRules,
		connect.WithSchema(gritzServiceMethods.ByName("SetRoutingRules")),
		connect.WithHandlerOptions(opts...),
	)
	gritzServiceGetEventTypesHandler := connect.NewUnaryHandlerSimple(
		GritzServiceGetEventTypesProcedure,
		svc.GetEventTypes,
		connect.WithSchema(gritzServiceMethods.ByName("GetEventTypes")),
		connect.WithHandlerOptions(opts...),
	)
	gritzServiceTestEventHandler := connect.NewUnaryHandlerSimple(
		GritzServiceTestEventProcedure,
		svc.TestEvent,
		connect.WithSchema(gritzServiceMethods.ByName("TestEvent")),
		connect.WithHandlerOptions(opts...),
	)
	gritzServiceCreateGitHubTokenHandler := connect.NewUnaryHandlerSimple(
		GritzServiceCreateGitHubTokenProcedure,
		svc.CreateGitHubToken,
		connect.WithSchema(gritzServiceMethods.ByName("CreateGitHubToken")),
		connect.WithHandlerOptions(opts...),
	)
	gritzServiceCreateScheduleHandler := connect.NewUnaryHandlerSimple(
		GritzServiceCreateScheduleProcedure,
		svc.CreateSchedule,
		connect.WithSchema(gritzServiceMethods.ByName("CreateSchedule")),
		connect.WithHandlerOptions(opts...),
	)
	gritzServiceGetScheduleHandler := connect.NewUnaryHandlerSimple(
		GritzServiceGetScheduleProcedure,
		svc.GetSchedule,
		connect.WithSchema(gritzServiceMethods.ByName("GetSchedule")),
		connect.WithHandlerOptions(opts...),
	)
	gritzServiceListSchedulesHandler := connect.NewUnaryHandlerSimple(
		GritzServiceListSchedulesProcedure,
		svc.ListSchedules,
		connect.WithSchema(gritzServiceMethods.ByName("ListSchedules")),
		connect.WithHandlerOptions(opts...),
	)
	gritzServiceUpdateScheduleHandler := connect.NewUnaryHandlerSimple(
		GritzServiceUpdateScheduleProcedure,
		svc.UpdateSchedule,
		connect.WithSchema(gritzServiceMethods.ByName("UpdateSchedule")),
		connect.WithHandlerOptions(opts...),
	)
	gritzServiceDeleteScheduleHandler := connect.NewUnaryHandlerSimple(
		GritzServiceDeleteScheduleProcedure,
		svc.DeleteSchedule,
		connect.WithSchema(gritzServiceMethods.ByName("DeleteSchedule")),
		connect.WithHandlerOptions(opts...),
	)
	gritzServiceSetScheduleEnabledHandler := connect.NewUnaryHandlerSimple(
		GritzServiceSetScheduleEnabledProcedure,
		svc.SetScheduleEnabled,
		connect.WithSchema(gritzServiceMethods.ByName("SetScheduleEnabled")),
		connect.WithHandlerOptions(opts...),
	)
	gritzServiceRunScheduleHandler := connect.NewUnaryHandlerSimple(
		GritzServiceRunScheduleProcedure,
		svc.RunSchedule,
		connect.WithSchema(gritzServiceMethods.ByName("RunSchedule")),
		connect.WithHandlerOptions(opts...),
	)
	return "/gritz.v1.GritzService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case GritzServicePingProcedure:
			gritzServicePingHandler.ServeHTTP(w, r)
		case GritzServiceGetProfileProcedure:
			gritzServiceGetProfileHandler.ServeHTTP(w, r)
		case GritzServiceListTasksProcedure:
			gritzServiceListTasksHandler.ServeHTTP(w, r)
		case GritzServiceListRunnerTasksProcedure:
			gritzServiceListRunnerTasksHandler.ServeHTTP(w, r)
		case GritzServiceCreateTaskProcedure:
			gritzServiceCreateTaskHandler.ServeHTTP(w, r)
		case GritzServiceGetTaskProcedure:
			gritzServiceGetTaskHandler.ServeHTTP(w, r)
		case GritzServiceUpdateTaskProcedure:
			gritzServiceUpdateTaskHandler.ServeHTTP(w, r)
		case GritzServiceArchiveTaskProcedure:
			gritzServiceArchiveTaskHandler.ServeHTTP(w, r)
		case GritzServiceUnarchiveTaskProcedure:
			gritzServiceUnarchiveTaskHandler.ServeHTTP(w, r)
		case GritzServiceCancelTaskProcedure:
			gritzServiceCancelTaskHandler.ServeHTTP(w, r)
		case GritzServiceRestartTaskProcedure:
			gritzServiceRestartTaskHandler.ServeHTTP(w, r)
		case GritzServiceOpenShellProcedure:
			gritzServiceOpenShellHandler.ServeHTTP(w, r)
		case GritzServiceUploadLogsProcedure:
			gritzServiceUploadLogsHandler.ServeHTTP(w, r)
		case GritzServiceCreateLinkProcedure:
			gritzServiceCreateLinkHandler.ServeHTTP(w, r)
		case GritzServiceListLinksProcedure:
			gritzServiceListLinksHandler.ServeHTTP(w, r)
		case GritzServiceListExternalEventsProcedure:
			gritzServiceListExternalEventsHandler.ServeHTTP(w, r)
		case GritzServiceGetEventProcedure:
			gritzServiceGetEventHandler.ServeHTTP(w, r)
		case GritzServiceDeleteEventProcedure:
			gritzServiceDeleteEventHandler.ServeHTTP(w, r)
		case GritzServiceListEventsByTaskProcedure:
			gritzServiceListEventsByTaskHandler.ServeHTTP(w, r)
		case GritzServiceSubmitRunnerEventsProcedure:
			gritzServiceSubmitRunnerEventsHandler.ServeHTTP(w, r)
		case GritzServiceCreateTaskTokenProcedure:
			gritzServiceCreateTaskTokenHandler.ServeHTTP(w, r)
		case GritzServiceRegisterWorkspacesProcedure:
			gritzServiceRegisterWorkspacesHandler.ServeHTTP(w, r)
		case GritzServiceListWorkspacesProcedure:
			gritzServiceListWorkspacesHandler.ServeHTTP(w, r)
		case GritzServiceClearWorkspacesProcedure:
			gritzServiceClearWorkspacesHandler.ServeHTTP(w, r)
		case GritzServiceCreateKeyProcedure:
			gritzServiceCreateKeyHandler.ServeHTTP(w, r)
		case GritzServiceListKeysProcedure:
			gritzServiceListKeysHandler.ServeHTTP(w, r)
		case GritzServiceDeleteKeyProcedure:
			gritzServiceDeleteKeyHandler.ServeHTTP(w, r)
		case GritzServiceUnlinkGitHubAccountProcedure:
			gritzServiceUnlinkGitHubAccountHandler.ServeHTTP(w, r)
		case GritzServiceLinkGitHubInstallationProcedure:
			gritzServiceLinkGitHubInstallationHandler.ServeHTTP(w, r)
		case GritzServiceUnlinkAtlassianAccountProcedure:
			gritzServiceUnlinkAtlassianAccountHandler.ServeHTTP(w, r)
		case GritzServiceCreateOrgProcedure:
			gritzServiceCreateOrgHandler.ServeHTTP(w, r)
		case GritzServiceListOrgsProcedure:
			gritzServiceListOrgsHandler.ServeHTTP(w, r)
		case GritzServiceDeleteOrgProcedure:
			gritzServiceDeleteOrgHandler.ServeHTTP(w, r)
		case GritzServiceAddOrgMemberProcedure:
			gritzServiceAddOrgMemberHandler.ServeHTTP(w, r)
		case GritzServiceRemoveOrgMemberProcedure:
			gritzServiceRemoveOrgMemberHandler.ServeHTTP(w, r)
		case GritzServiceListOrgMembersProcedure:
			gritzServiceListOrgMembersHandler.ServeHTTP(w, r)
		case GritzServiceGetOrgSettingsProcedure:
			gritzServiceGetOrgSettingsHandler.ServeHTTP(w, r)
		case GritzServiceGenerateAtlassianWebhookSecretProcedure:
			gritzServiceGenerateAtlassianWebhookSecretHandler.ServeHTTP(w, r)
		case GritzServiceGetRoutingRulesProcedure:
			gritzServiceGetRoutingRulesHandler.ServeHTTP(w, r)
		case GritzServiceSetRoutingRulesProcedure:
			gritzServiceSetRoutingRulesHandler.ServeHTTP(w, r)
		case GritzServiceGetEventTypesProcedure:
			gritzServiceGetEventTypesHandler.ServeHTTP(w, r)
		case GritzServiceTestEventProcedure:
			gritzServiceTestEventHandler.ServeHTTP(w, r)
		case GritzServiceCreateGitHubTokenProcedure:
			gritzServiceCreateGitHubTokenHandler.ServeHTTP(w, r)
		case GritzServiceCreateScheduleProcedure:
			gritzServiceCreateScheduleHandler.ServeHTTP(w, r)
		case GritzServiceGetScheduleProcedure:
			gritzServiceGetScheduleHandler.ServeHTTP(w, r)
		case GritzServiceListSchedulesProcedure:
			gritzServiceListSchedulesHandler.ServeHTTP(w, r)
		case GritzServiceUpdateScheduleProcedure:
			gritzServiceUpdateScheduleHandler.ServeHTTP(w, r)
		case GritzServiceDeleteScheduleProcedure:
			gritzServiceDeleteScheduleHandler.ServeHTTP(w, r)
		case GritzServiceSetScheduleEnabledProcedure:
			gritzServiceSetScheduleEnabledHandler.ServeHTTP(w, r)
		case GritzServiceRunScheduleProcedure:
			gritzServiceRunScheduleHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedGritzServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedGritzServiceHandler struct{}

func (UnimplementedGritzServiceHandler) Ping(context.Context, *v1.PingRequest) (*v1.PingResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gritz.v1.GritzService.Ping is not implemented"))
}

func (UnimplementedGritzServiceHandler) GetProfile(context.Context, *v1.GetProfileRequest) (*v1.GetProfileResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gritz.v1.GritzService.GetProfile is not implemented"))
}

func (UnimplementedGritzServiceHandler) ListTasks(context.Context, *v1.ListTasksRequest) (*v1.ListTasksResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gritz.v1.GritzService.ListTasks is not implemented"))
}

func (UnimplementedGritzServiceHandler) ListRunnerTasks(context.Context, *v1.ListRunnerTasksRequest) (*v1.ListRunnerTasksResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gritz.v1.GritzService.ListRunnerTasks is not implemented"))
}

func (UnimplementedGritzServiceHandler) CreateTask(context.Context, *v1.CreateTaskRequest) (*v1.CreateTaskResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gritz.v1.GritzService.CreateTask is not implemented"))
}

func (UnimplementedGritzServiceHandler) GetTask(context.Context, *v1.GetTaskRequest) (*v1.GetTaskResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gritz.v1.GritzService.GetTask is not implemented"))
}

func (UnimplementedGritzServiceHandler) UpdateTask(context.Context, *v1.UpdateTaskRequest) (*v1.UpdateTaskResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gritz.v1.GritzService.UpdateTask is not implemented"))
}

func (UnimplementedGritzServiceHandler) ArchiveTask(context.Context, *v1.ArchiveTaskRequest) (*v1.ArchiveTaskResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gritz.v1.GritzService.ArchiveTask is not implemented"))
}

func (UnimplementedGritzServiceHandler) UnarchiveTask(context.Context, *v1.UnarchiveTaskRequest) (*v1.UnarchiveTaskResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gritz.v1.GritzService.UnarchiveTask is not implemented"))
}

func (UnimplementedGritzServiceHandler) CancelTask(context.Context, *v1.CancelTaskRequest) (*v1.CancelTaskResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gritz.v1.GritzService.CancelTask is not implemented"))
}

func (UnimplementedGritzServiceHandler) RestartTask(context.Context, *v1.RestartTaskRequest) (*v1.RestartTaskResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gritz.v1.GritzService.RestartTask is not implemented"))
}

func (UnimplementedGritzServiceHandler) OpenShell(context.Context, *v1.OpenShellRequest) (*v1.OpenShellResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gritz.v1.GritzService.OpenShell is not implemented"))
}

func (UnimplementedGritzServiceHandler) UploadLogs(context.Context, *v1.UploadLogsRequest) (*v1.UploadLogsResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gritz.v1.GritzService.UploadLogs is not implemented"))
}

func (UnimplementedGritzServiceHandler) CreateLink(context.Context, *v1.CreateLinkRequest) (*v1.CreateLinkResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gritz.v1.GritzService.CreateLink is not implemented"))
}

func (UnimplementedGritzServiceHandler) ListLinks(context.Context, *v1.ListLinksRequest) (*v1.ListLinksResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gritz.v1.GritzService.ListLinks is not implemented"))
}

func (UnimplementedGritzServiceHandler) ListExternalEvents(context.Context, *v1.ListExternalEventsRequest) (*v1.ListExternalEventsResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gritz.v1.GritzService.ListExternalEvents is not implemented"))
}

func (UnimplementedGritzServiceHandler) GetEvent(context.Context, *v1.GetEventRequest) (*v1.GetEventResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gritz.v1.GritzService.GetEvent is not implemented"))
}

func (UnimplementedGritzServiceHandler) DeleteEvent(context.Context, *v1.DeleteEventRequest) (*v1.DeleteEventResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gritz.v1.GritzService.DeleteEvent is not implemented"))
}

func (UnimplementedGritzServiceHandler) ListEventsByTask(context.Context, *v1.ListEventsByTaskRequest) (*v1.ListEventsByTaskResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gritz.v1.GritzService.ListEventsByTask is not implemented"))
}

func (UnimplementedGritzServiceHandler) SubmitRunnerEvents(context.Context, *v1.SubmitRunnerEventsRequest) (*v1.SubmitRunnerEventsResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gritz.v1.GritzService.SubmitRunnerEvents is not implemented"))
}

func (UnimplementedGritzServiceHandler) CreateTaskToken(context.Context, *v1.CreateTaskTokenRequest) (*v1.CreateTaskTokenResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gritz.v1.GritzService.CreateTaskToken is not implemented"))
}

func (UnimplementedGritzServiceHandler) RegisterWorkspaces(context.Context, *v1.RegisterWorkspacesRequest) (*v1.RegisterWorkspacesResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gritz.v1.GritzService.RegisterWorkspaces is not implemented"))
}

func (UnimplementedGritzServiceHandler) ListWorkspaces(context.Context, *v1.ListWorkspacesRequest) (*v1.ListWorkspacesResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gritz.v1.GritzService.ListWorkspaces is not implemented"))
}

func (UnimplementedGritzServiceHandler) ClearWorkspaces(context.Context, *v1.ClearWorkspacesRequest) (*v1.ClearWorkspacesResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gritz.v1.GritzService.ClearWorkspaces is not implemented"))
}

func (UnimplementedGritzServiceHandler) CreateKey(context.Context, *v1.CreateKeyRequest) (*v1.CreateKeyResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gritz.v1.GritzService.CreateKey is not implemented"))
}

func (UnimplementedGritzServiceHandler) ListKeys(context.Context, *v1.ListKeysRequest) (*v1.ListKeysResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gritz.v1.GritzService.ListKeys is not implemented"))
}

func (UnimplementedGritzServiceHandler) DeleteKey(context.Context, *v1.DeleteKeyRequest) (*v1.DeleteKeyResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gritz.v1.GritzService.DeleteKey is not implemented"))
}

func (UnimplementedGritzServiceHandler) UnlinkGitHubAccount(context.Context, *v1.UnlinkGitHubAccountRequest) (*v1.UnlinkGitHubAccountResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gritz.v1.GritzService.UnlinkGitHubAccount is not implemented"))
}

func (UnimplementedGritzServiceHandler) LinkGitHubInstallation(context.Context, *v1.LinkGitHubInstallationRequest) (*v1.LinkGitHubInstallationResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gritz.v1.GritzService.LinkGitHubInstallation is not implemented"))
}

func (UnimplementedGritzServiceHandler) UnlinkAtlassianAccount(context.Context, *v1.UnlinkAtlassianAccountRequest) (*v1.UnlinkAtlassianAccountResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gritz.v1.GritzService.UnlinkAtlassianAccount is not implemented"))
}

func (UnimplementedGritzServiceHandler) CreateOrg(context.Context, *v1.CreateOrgRequest) (*v1.CreateOrgResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gritz.v1.GritzService.CreateOrg is not implemented"))
}

func (UnimplementedGritzServiceHandler) ListOrgs(context.Context, *v1.ListOrgsRequest) (*v1.ListOrgsResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gritz.v1.GritzService.ListOrgs is not implemented"))
}

func (UnimplementedGritzServiceHandler) DeleteOrg(context.Context, *v1.DeleteOrgRequest) (*v1.DeleteOrgResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gritz.v1.GritzService.DeleteOrg is not implemented"))
}

func (UnimplementedGritzServiceHandler) AddOrgMember(context.Context, *v1.AddOrgMemberRequest) (*v1.AddOrgMemberResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gritz.v1.GritzService.AddOrgMember is not implemented"))
}

func (UnimplementedGritzServiceHandler) RemoveOrgMember(context.Context, *v1.RemoveOrgMemberRequest) (*v1.RemoveOrgMemberResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gritz.v1.GritzService.RemoveOrgMember is not implemented"))
}

func (UnimplementedGritzServiceHandler) ListOrgMembers(context.Context, *v1.ListOrgMembersRequest) (*v1.ListOrgMembersResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gritz.v1.GritzService.ListOrgMembers is not implemented"))
}

func (UnimplementedGritzServiceHandler) GetOrgSettings(context.Context, *v1.GetOrgSettingsRequest) (*v1.GetOrgSettingsResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gritz.v1.GritzService.GetOrgSettings is not implemented"))
}

func (UnimplementedGritzServiceHandler) GenerateAtlassianWebhookSecret(context.Context, *v1.GenerateAtlassianWebhookSecretRequest) (*v1.GenerateAtlassianWebhookSecretResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gritz.v1.GritzService.GenerateAtlassianWebhookSecret is not implemented"))
}

func (UnimplementedGritzServiceHandler) GetRoutingRules(context.Context, *v1.GetRoutingRulesRequest) (*v1.GetRoutingRulesResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gritz.v1.GritzService.GetRoutingRules is not implemented"))
}

func (UnimplementedGritzServiceHandler) SetRoutingRules(context.Context, *v1.SetRoutingRulesRequest) (*v1.SetRoutingRulesResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gritz.v1.GritzService.SetRoutingRules is not implemented"))
}

func (UnimplementedGritzServiceHandler) GetEventTypes(context.Context, *v1.GetEventTypesRequest) (*v1.GetEventTypesResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gritz.v1.GritzService.GetEventTypes is not implemented"))
}

func (UnimplementedGritzServiceHandler) TestEvent(context.Context, *v1.TestEventRequest) (*v1.TestEventResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gritz.v1.GritzService.TestEvent is not implemented"))
}

func (UnimplementedGritzServiceHandler) CreateGitHubToken(context.Context, *v1.CreateGitHubTokenRequest) (*v1.CreateGitHubTokenResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gritz.v1.GritzService.CreateGitHubToken is not implemented"))
}

func (UnimplementedGritzServiceHandler) CreateSchedule(context.Context, *v1.CreateScheduleRequest) (*v1.CreateScheduleResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gritz.v1.GritzService.CreateSchedule is not implemented"))
}

func (UnimplementedGritzServiceHandler) GetSchedule(context.Context, *v1.GetScheduleRequest) (*v1.GetScheduleResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gritz.v1.GritzService.GetSchedule is not implemented"))
}

func (UnimplementedGritzServiceHandler) ListSchedules(context.Context, *v1.ListSchedulesRequest) (*v1.ListSchedulesResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gritz.v1.GritzService.ListSchedules is not implemented"))
}

func (UnimplementedGritzServiceHandler) UpdateSchedule(context.Context, *v1.UpdateScheduleRequest) (*v1.UpdateScheduleResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gritz.v1.GritzService.UpdateSchedule is not implemented"))
}

func (UnimplementedGritzServiceHandler) DeleteSchedule(context.Context, *v1.DeleteScheduleRequest) (*v1.DeleteScheduleResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gritz.v1.GritzService.DeleteSchedule is not implemented"))
}

func (UnimplementedGritzServiceHandler) SetScheduleEnabled(context.Context, *v1.SetScheduleEnabledRequest) (*v1.SetScheduleEnabledResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gritz.v1.GritzService.SetScheduleEnabled is not implemented"))
}

func (UnimplementedGritzServiceHandler) RunSchedule(context.Context, *v1.RunScheduleRequest) (*v1.RunScheduleResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gritz.v1.GritzService.RunSchedule is not implemented"))
}
