// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: logchunk.sql

package sqlc

import (
	"context"
	"time"
)

const createLogChunk = `-- name: CreateLogChunk :one
INSERT INTO log_chunks (org_id, task_id, version, data, created_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type CreateLogChunkParams struct {
	OrgID     int64     `json:"org_id"`
	TaskID    int64     `json:"task_id"`
	Version   int64     `json:"version"`
	Data      []byte    `json:"data"`
	CreatedAt time.Time `json:"created_at"`
}

// Inserts one log chunk. One chunk per statement is what makes id order write
// order: the driver ships with a single in-flight sender, so the bigserial is
// assigned in the order the bytes were written, by construction rather than by
// any assumption about how a multi-row insert orders its rows.
func (q *Queries) CreateLogChunk(ctx context.Context, arg CreateLogChunkParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createLogChunk,
		arg.OrgID,
		arg.TaskID,
		arg.Version,
		arg.Data,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listLogChunksByTaskAsc = `-- name: ListLogChunksByTaskAsc :many
SELECT id, org_id, task_id, version, data, created_at
FROM log_chunks
WHERE task_id = $1
  AND org_id = $2
  AND id > $3::bigint
ORDER BY id ASC
LIMIT $4
`

type ListLogChunksByTaskAscParams struct {
	TaskID    int64 `json:"task_id"`
	OrgID     int64 `json:"org_id"`
	CursorID  int64 `json:"cursor_id"`
	PageLimit int32 `json:"page_limit"`
}

// Live-follow slice (id > cursor), ascending. Backs the pagination-backward
// walk. Covered by idx_log_chunks_task_id_id (no new migration).
func (q *Queries) ListLogChunksByTaskAsc(ctx context.Context, arg ListLogChunksByTaskAscParams) ([]LogChunk, error) {
	rows, err := q.db.QueryContext(ctx, listLogChunksByTaskAsc,
		arg.TaskID,
		arg.OrgID,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LogChunk{}
	for rows.Next() {
		var i LogChunk
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.TaskID,
			&i.Version,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLogChunksByTaskDesc = `-- name: ListLogChunksByTaskDesc :many
SELECT id, org_id, task_id, version, data, created_at
FROM log_chunks
WHERE task_id = $1
  AND org_id = $2
  AND (NOT $3::bool OR id < $4::bigint)
ORDER BY id DESC
LIMIT $5
`

type ListLogChunksByTaskDescParams struct {
	TaskID    int64 `json:"task_id"`
	OrgID     int64 `json:"org_id"`
	UseCursor bool  `json:"use_cursor"`
	CursorID  int64 `json:"cursor_id"`
	PageLimit int32 `json:"page_limit"`
}

// Newest-first slice: the newest page (no cursor) and scroll-back (id < cursor).
// Backs the pagination-forward (primary) walk; List reverses to ascending for
// display. Covered by idx_log_chunks_task_id_id (no new migration).
func (q *Queries) ListLogChunksByTaskDesc(ctx context.Context, arg ListLogChunksByTaskDescParams) ([]LogChunk, error) {
	rows, err := q.db.QueryContext(ctx, listLogChunksByTaskDesc,
		arg.TaskID,
		arg.OrgID,
		arg.UseCursor,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LogChunk{}
	for rows.Next() {
		var i LogChunk
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.TaskID,
			&i.Version,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
